require:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-rspec
  - rubocop-rspec_rails
AllCops:
  Exclude:
    - 'Gemfile'
    - 'db/schema.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 12